### ISSUE TITLE
Get ready for 1.0.0

### ISSUE THREAD

**Issue by briancavalier** [cujojs/most#122]
What do we need to do to feel good about releasing 1.0.0?

- [x] remove deprecated functions/methods (#124)
- [x] remove "experimental" flag from `during`(#128)
- [x] deprecate `lift` (#125 deprecated in 0.14.0)
- [x] remove `lift`

**Comment by briancavalier** [comment]
I think #20 may be a good candidate for 1.0.

**Comment by briancavalier** [comment]
We should remove all currently deprecated functions for 1.0 :rocket:

**Comment by briancavalier** [comment]
Remove the "experimental" status of `during`.

**Comment by briancavalier** [comment]
If we curry the functional API, then `lift` becomes redundant to `map` and `combine`, so we should deprecate it.  IOW, `most.lift(f)` is equivalent to `most.map(f)` for 1-ary functions and to `most.combine(f)` for 2+-ary functions.

**Comment by unscriptable** [comment]
> If we curry the functional API, then `lift` becomes redundant to `map` and `combine`

I'm in agreement that `lift` is redundant, but it wasn't immediately obvious to me that `combine` is the way to "lift" higher-arity functions.  Is there a way we can get something into the docs?

**Comment by briancavalier** [comment]
Yeah, we'll probably need to add a general section on using curried functions.

**Comment by briancavalier** [comment]
Ok, postponing currying until later.

**Comment by briancavalier** [comment]
Since we released 0.14.0 with deprecated `lift`, I think we should remove `lift` for 1.0.0.

**Comment by PhiLhoSoft** [comment]
Not sure if I should open a new issue, but this one seems fitting... :smile: 
I am looking at the API doc, and clicking on some functions in the summary, like most.repeat, does nothing. And, indeed, it seems it is gone.
So my comment here is: "don't forget to clean up the ToC of your doc". :wink:

**Comment by briancavalier** [comment]
Thanks for the nudge @PhiLhoSoft! :)

**Comment by jeffutter** [comment]
I don't see lift in the codebase anymore. Is this done? Are there other things on the roadmap for 1.0.0?

**Comment by briancavalier** [comment]
Hey @jeffutter, yeah, it was deprecated and then removed.

We also recently moved the [roadmap to the wiki](https://github.com/cujojs/most/wiki/Roadmap).  We're currently working out which of those things belongs in 1.0.0.

We should probably close this issue as well.  Sorry for any confusion it caused.

**Comment by jeffutter** [comment]
@briancavalier No problem. I was just looking for something to contribute to and found this issue which seemed stale. Thanks for the pointer to the roadmap.
